



INSERT INTO burgers(BURGER_NAME, DEVOURED) VALUES ('CHEESE BURGER',FALSE);
INSERT INTO burgers(BURGER_NAME, DEVOURED) VALUES ('HAM BURGER',FALSE);
INSERT INTO burgers(BURGER_NAME, DEVOURED) VALUES ('CHICKEN BURGER',FALSE);
INSERT INTO burgers(BURGER_NAME, DEVOURED) VALUES (' BACON BURGER',TRUE);